name: Check Syntax

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # 最新のバージョンを使用
    - name: Set up Python
      uses: actions/setup-python@v2  # setup-pythonの最新バージョン
      with:
        python-version: 3.11  # 利用可能なバージョンに変更
    - name: Install dependencies
      run: python -m pip install discord.py[voice] flake8
    - name: Run flake8
      run: flake8 --ignore=E302,E501
